GCI_BIN_DIR    = $(PROJ_TOP_DIR)/bin
GCI_CONFIG_DIR = $(PROJ_TOP_DIR)/config
GCI_DATA_DIR   = $(PROJ_TOP_DIR)/data
GCI_LIB_DIR    = $(PROJ_TOP_DIR)/src
GCI_TEST_DIR   = $(PROJ_TOP_DIR)/test
GCI_VAR_DIR    = $(PROJ_TOP_DIR)/var

BIN_DIR    		= $(PROJECT_DIR)/bin
VAR_DIR    		= $(PROJECT_DIR)/vendor
TEST_DIR    	= $(PROJECT_DIR)/tests

ALL_TARGETS += last-build
BUILD_TARGETS += initialize
CHECK_TARGETS +=
CLEAN_TARGETS +=
DISTCLEAN_TARGETS += clean
INITIALIZE_TARGETS += install
INSTALL_TARGETS +=
LAST_BUILD_TARGETS += build
TEST_TARGETS +=
