export COMPOSER_ALLOW_SUPERUSER=1
COMPOSER_ALLOW_SUPERUSER=1

COMPOSER = $(BIN_DIR)/composer.phar
COMPOSER_COMMANDS +=
COMPOSER_JSON = $(PROJECT_DIR)/composer.json
COMPOSER_LAST_UPDATE = $(BIN_DIR)/.last-update
COMPOSER_LOCK = $(PROJECT_DIR)/composer.lock
