#GIT_PROJECT_REPO = $(PROJECT_DIR)/.git
#
#GIT_HOOKS_DIR = $(GIT_PROJECT_REPO)/hooks
#GIT_HOOKS_INIT_FILE = $(GIT_HOOKS_DIR)/.init.sh
#GIT_HOOKS_PRE_COMMIT = $(GIT_HOOKS_DIR)/pre-commit
#
#GIT_TEMPLATE_DIR = $(PROJ_TOP_DIR)/.git_template/hooks
#GIT_TEMPLATE_INIT_FILE = $(GIT_TEMPLATE_DIR)/.init.sh
#GIT_TEMPLATE_PRE_COMMIT = $(GIT_TEMPLATE_DIR)/pre-commit
